# Generated by Django 4.0.6 on 2022-08-03 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_lib', '0001_squashed_0002_alter_author_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('products', models.ManyToManyField(related_name='stores', to='web_lib.product')),
            ],
        ),
    ]
