# Generated by Django 4.0.6 on 2022-08-01 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0002_home_product_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='home',
            name='bal',
            field=models.BooleanField(default=True, verbose_name='Балкон'),
        ),
    ]
